### ISSUE TITLE
Proxy tool login

### ISSUE THREAD

**Issue by teopost** [shurrey/BBDN-Web-Service-Python-Sample-Code#2]
Can you explain how I can authenticate with proxy tool ?

I should change this line ?

```
loggedIn = contextWS.service.login("user", "password", "bb", "blackboard", "", 3600)
```

**Comment by shurrey** [comment]
You would call it like this:

`
        # Initialize headers and then call createHeaders to generate the soap headers with WSSE bits.
        headers = []
        headers = createHeaders('loginTool', 'session', sessionId, 'Context.WS')

```
    # Add Headers and WS-Security to client. Set port to default value, otherwise, you must add to service call
    contextWS.set_options(soapheaders=headers, port='Context.WSSOAP12port_https')

    # Login as tool. 
    logged_in = contextWS.service.loginTool(shared_password, vendor_id, program_id, "", 3600)
    if DEBUG == True:
        print(logged_in)
```

`

For an example, check out my other project [here](https://github.com/blackboard/BBDN-WsSoapPythonWorkshop).

**Comment by teopost** [comment]
Wow. This link is beautiful.

Thankyou

2016-03-07 18:15 GMT+01:00 Scott Hurrey notifications@github.com:

> You would call it like this:
> 
> `
> 
> # Initialize headers and then call createHeaders to generate the soap
> 
> headers with WSSE bits.
> headers = []
> headers = createHeaders('loginTool', 'session', sessionId, 'Context.WS')
> 
> ```
> # Add Headers and WS-Security to client. Set port to default value, otherwise, you must add to service call
> contextWS.set_options(soapheaders=headers, port='Context.WSSOAP12port_https')
> 
> # Login as tool.
> logged_in = contextWS.service.loginTool(shared_password, vendor_id, program_id, "", 3600)
> if DEBUG == True:
>     print(logged_in)
> ```
> 
> `
> 
> For an example, check out my other project here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blackboard/BBDN-Web-Service-Python-Sample-Code/issues/2#issuecomment-193353469
> .

## 

Stefano Teodorani
s.teodorani@gmail.com

**Comment by shurrey** [comment]
Glad I could help. Happy Developing!

**Comment by teopost** [comment]
there are REST web service?

2016-03-07 18:18 GMT+01:00 Stefano Teodorani s.teodorani@gmail.com:

> Wow. This link is beautiful.
> 
> Thankyou
> 
> 2016-03-07 18:15 GMT+01:00 Scott Hurrey notifications@github.com:
> 
> > You would call it like this:
> > 
> > `
> > 
> > # Initialize headers and then call createHeaders to generate the soap
> > 
> > headers with WSSE bits.
> > headers = []
> > headers = createHeaders('loginTool', 'session', sessionId, 'Context.WS')
> > 
> > ```
> > # Add Headers and WS-Security to client. Set port to default value, otherwise, you must add to service call
> > contextWS.set_options(soapheaders=headers, port='Context.WSSOAP12port_https')
> > 
> > # Login as tool.
> > logged_in = contextWS.service.loginTool(shared_password, vendor_id, program_id, "", 3600)
> > if DEBUG == True:
> >     print(logged_in)
> > ```
> > 
> > `
> > 
> > For an example, check out my other project here.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/blackboard/BBDN-Web-Service-Python-Sample-Code/issues/2#issuecomment-193353469
> > .
> 
> ## 
> 
> Stefano Teodorani
> s.teodorani@gmail.com

## 

Stefano Teodorani
s.teodorani@gmail.com

**Comment by shurrey** [comment]
Coming soon... We are currently doing a series of webinars on this topic. Check out the [community site](https://community.blackboard.com/community/developers/rest) for more information.

You will need a community login if you don't have one. You can click to register on the login page, and then you will just need one of the admins to approve your account. Usually only takes a few hours. 

Also, April 4 in Holland (Groningen), we are putting on a Developers Conference, and we will be talking a lot about the REST services. You can read more about it [here](http://experience.blackboard.com/Groningen2016/pre-conference-events/devcon/).
